apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5.conf
  namespace: jupyterhub
data:
  config: |
    [libdefaults]
    	default_realm = AD.${ENVIRONMENT}.${DOMAIN}
    	kdc_timesync = 1
    	ccache_type = 4
    	forwardable = true
    	proxiable = true
      
    [realms]
    AD.${ENVIRONMENT}.${DOMAIN} = {
    }
    
    [domain_realm]
    .AD.${ENVIRONMENT}.${DOMAIN} = AD.${ENVIRONMENT}.${DOMAIN}
    .AD = AD.${ENVIRONMENT}.${DOMAIN}
    AD = AD.${ENVIRONMENT}.${DOMAIN}    

  
apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5.conf
  namespace: ad
data:
  config: |
    [libdefaults]
    	default_realm = AD.${ENVIRONMENT}.${DOMAIN}
    	kdc_timesync = 1
    	ccache_type = 4
    	forwardable = true
    	proxiable = true
      
    [realms]
    AD.${ENVIRONMENT}.${DOMAIN} = {
    }
    
    [domain_realm]
    .AD.${ENVIRONMENT}.${DOMAIN} = AD.${ENVIRONMENT}.${DOMAIN}
    .AD = AD.${ENVIRONMENT}.${DOMAIN}
    AD = AD.${ENVIRONMENT}.${DOMAIN}    
  
