apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ad-service.yaml
  - keytab-job.yaml
  - mssql-service.yaml


configMapGenerator:
  - name: keytab-job.sh
    files:
      - keytab-job.sh
