apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccache-generator
  namespace: ad
automountServiceAccountToken: true

---
# This role allows the ccache job to fetch users, groups and projects,
# so that it can create a kerberos ticket cache file for each.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: samba-identity-fetcher
  namespace: ad
rules:
  - apiGroups: ["identity.k8tre.io", "research.k8tre.io"]
    resources: ["users", "groups", "projects"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: samba-cache-generator
  namespace: ad
rules:
  - apiGroups: [""]
    resources: ["configmap"]
    verbs: ["create", "update", "list", "delete", "get"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samba-identity-fetcher
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: ccache-generator
    namespace: ad
roleRef:
  kind: Role
  name: samba-identity-fetcher
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samba-ccache-generator
  namespace: ad
subjects:
  - kind: ServiceAccount
    name: ccache-generator
    namespace: ad
roleRef:
  kind: Role
  name: samba-ccache-generator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccache-generator
  namespace: ad
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ccache-generator
          restartPolicy: OnFailure
          volumes:
            - name: ccache
              configMap:
                defaultMode: 0600
                name: samba-admin
          containers:
          - name: ccache-generator
            image: docker.io/library/samba-dc:latest
            imagePullPolicy: Never
            volumeMounts:
              - mountPath: /Administrator.ccache
                name: ccache
                subPath: Administrator.ccache
            command:
            - /bin/sh
            - -c
            - |
              mkdir /samba/etc
              cat > /etc/samba/smb.conf <<CONF
              [global]
              tls verify peer = no_check
              CONF

              cat > /etc/krb5.conf <<CONF
              [libdefaults]
              default_realm = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
              dns_lookup_realm = false
              dns_lookup_kdc = true
              rdns = false

              [realms]
              AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK = {
              default_domain = ad.stg.asjk8tre.dev.hic.dundee.ac.uk
              kdc = dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk
              }
              CONF

              date
              echo "Updating Kerberos ccahe ConfigMaps"
              kubectl -n keycloak get users
              kubectl -n keycloak get projects
              kubectl -n keycloak get groups
              klist -c /Administrator.ccache

              exit 0
              username=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 10)
              samba-tool user add "$username" -d10 -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                    -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache --random-password
              exit 0
