apiVersion: v1
kind: ServiceAccount
metadata:
  name: keytab-generator
  namespace: ad
automountServiceAccountToken: true

---
# This role allows the ccache job to fetch users, groups and projects,
# so that it can create a kerberos ticket cache file for each.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: samba-identity-fetcher
  namespace: keycloak
rules:
  - apiGroups: ["identity.k8tre.io", "research.k8tre.io"]
    resources: ["users", "groups", "projects"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: samba-keytab-generator
  namespace: ad
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "list", "delete", "get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: samba-keytab-generator
  namespace: jupyterhub
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "list", "delete", "get", "patch"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samba-identity-fetcher
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: keytab-generator
    namespace: ad
roleRef:
  kind: Role
  name: samba-identity-fetcher
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samba-keytab-generator
  namespace: ad
subjects:
  - kind: ServiceAccount
    name: keytab-generator
    namespace: ad
roleRef:
  kind: Role
  name: samba-keytab-generator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samba-keytab-generator
  namespace: jupyterhub
subjects:
  - kind: ServiceAccount
    name: keytab-generator
    namespace: ad
roleRef:
  kind: Role
  name: samba-keytab-generator
  apiGroup: rbac.authorization.k8s.io
  
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: keytab-generator
  namespace: ad
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: keytab-generator
          restartPolicy: OnFailure
          volumes:
            - name: ccache
              configMap:
                defaultMode: 0600
                name: administrator.keytab
          containers:
          - name: keytab-generator
            image: docker.io/library/samba-dc:latest
            imagePullPolicy: Never
            volumeMounts:
              - mountPath: /Administrator.keytab
                name: ccache
                subPath: Administrator.keytab
            command:
            - /bin/sh
            - -c
            - |
              mkdir /samba/etc
              cat > /etc/samba/smb.conf <<CONF
              [global]
                  tls verify peer = no_check
              CONF

              cat > /etc/krb5.conf <<CONF
              [libdefaults]
              default_realm = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
              dns_lookup_realm = false
              dns_lookup_kdc = true
              rdns = false

              [realms]
              AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK = {
                  default_domain = ad.stg.asjk8tre.dev.hic.dundee.ac.uk
                  kdc = dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk
              }
              CONF

              date
              echo "Updating Kerberos keytab ConfigMaps"
              kinit -k -t /Administrator.keytab -c Administrator.ccache Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK

              current_users=$(samba-tool user list -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                  -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache)
              current_groups=$(samba-tool group list -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                  -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache)

              # CRDs for this are a bit messy.
              # 
              # `group.identity.k8tre.io` has two valid schemas
              # depending on whether it's a subgroup or not. In the
              # case of subgroup, it defines project as a list, when
              # it should probably be limited to a single project.
              #
              # We can filter out the ones we want by checking for
              # .spec.members
              kubectl  -n keycloak get group -o yaml | yq -r '.items[] | select(.spec.members) | .spec | (.projects[0])' | sort -u > /tmp/projects.txt
              while read project <&3 ; do
                  # Create a user group in AD if it doesn't exist already.
                  (echo "$current_groups" | grep "^project-$project$" >/dev/null) || (
                      samba-tool group add "project-$project" -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                          -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache
                  )
              done 3< /tmp/projects.txt
              
              kubectl  -n keycloak get group -o yaml | yq -r '.items[] | select(.spec.members) | .spec | (.members[] + "-" + .projects[0] + "\t" + .projects[0])' > /tmp/usernames.txt
              while read username project <&3 ; do
                  (echo "$current_users" | grep "^$username$" >/dev/null) || (
                      samba-tool user add "$username" -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                          -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache --random-password

                      samba-tool group addmembers "project-$project" "$username" -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                          -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache

                      password=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 32)
                      samba-tool user setpassword "$username" --newpassword "$password" -H ldaps://dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk \
                          -U Administrator@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK --use-kerberos=required --use-krb5-ccache=/Administrator.ccache

                      # Create a keytab for this user principal. This only needs to be regenerated if the user's password changes.
                      # It also needs to be moved over to an expect script cause this is a bit rubbish.
                      (
                      echo "clear"
                      echo "addent -password -p $username@AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK -k 1 -e aes256-cts-hmac-sha1-96"
                      echo "$password"
                      echo "wkt /keytab"
                      ) | ktutil

                      kubectl -n jupyterhub create configmap "$username.keytab" --from-file /keytab -o yaml --dry-run=client | kubectl apply -f -

                      rm /keytab
                  )
                  
              done 3< /tmp/usernames.txt
              exit 0
