apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: ad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-krb5.conf
  namespace: ad
data:
  krb5.conf: |
    [libdefaults]
    default_realm = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
    default_keytab_file = /var/opt/mssql/secrets/mssql.keytab
    default_ccache_name = ""
    kdc = dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk
    kdc_timesync = 1
    ccache_type = 4
    forwardable = true
    proxiable = true
    default_tgs_enctypes = AES128-CTS-HMAC-SHA1-96 
    default_tkt_enctypes = AES128-CTS-HMAC-SHA1-96
    fast_fail = false
    disable_fast = true
    
    [realms]
    AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK = {
        kdc = dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk
        admin_server = dc0.ad.stg.asjk8tre.dev.hic.dundee.ac.uk
        default_domain = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
    }
    
    [domain_realm]
    AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
    AD = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK    
    .AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK
    .ad.stg.asjk8tre.dev.hic.dundee.ac.uk = AD.STG.ASJK8TRE.DEV.HIC.DUNDEE.AC.UK

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql.conf
  namespace: ad
data:
  mssql.conf: |
    [network]
    privilegedadaccount = MSSQL
    kerberoskeytabfile = /var/opt/mssql/secrets/mssql.keytab
    disablesssd = true
    enablekdcfromkrb5conf = true

  logger.ini: |
    [Output:security]
    Type = File
    Filename = /var/opt/mssql/log/security.log

    [Logger]
    Level = Silent

    [Logger:security.kerberos]
    Level = debug
    Outputs = security
    [Logger:security.ldap]
    Level = debug
    Outputs = security
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      hostname: sql      
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-data
        - name: mssql-keytab
          configMap:
            name: mssql.keytab
            defaultMode: 0660
        - name: mssql-krb5
          configMap:
            name: mssql-krb5.conf
            defaultMode: 0444
        - name: mssql-conf
          configMap:
            name: mssql.conf
            defaultMode: 444
      securityContext:
        fsGroup: 10001            
      containers:
        - name: mssql
          image: docker.io/library/mssql-k8tre:latest
          imagePullPolicy: Never
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "MSSQL_SA_PASSWORD"
              value: "X2T%Tp5b89V%WzXD!tq"
            - name: "KRB5_TRACE"
              value: "/dev/stdout"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql/data
            - name: mssql-keytab
              subPath: mssql.keytab
              mountPath: /var/opt/mssql/secrets/mssql.keytab
            - name: mssql-krb5
              subPath: krb5.conf
              mountPath: /etc/krb5.conf
            - name: mssql-conf
              subPath: mssql.conf
              mountPath: /var/opt/mssql/mssql.conf
            - name: mssql-conf
              subPath: logger.ini
              mountPath: /var/opt/mssql/logger.ini              
          ports:
            - containerPort: 1433
              protocol: TCP
      dnsConfig:
        searches:
          - ad.stg.asjk8tre.dev.hic.dundee.ac.uk
          - stg.asjk8tre.dev.hic.dundee.ac.uk
              
---
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: ad
spec:
  selector:
    app: mssql
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
      protocol: TCP
